name: Cross-Platform System Info

on: [push]

jobs:
    ubuntu-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Print system info
              run: |
                  echo "OS: $(uname -a)"
                  echo "Disk usagee:"
                  df -h
                  echo "CPU info:"
                  lscpu || true

            - name: Capture metadata
              run: |
                  echo "Commit SHA: ${{ github.sha }}" > metadata.txt
                  echo "Repository: ${{ github.repository }}" >> metadata.txt
                  echo "Workspace: $GITHUB_WORKSPACE" >> metadata.txt

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ubuntu-metadata
                  path: metadata.txt
