name: Stale issues and PRs
on:
    schedule:
        # - cron: "0 14 * * *" # everyday at 2pm
        - cron: "*/5 * * * *" #every 1 min

permissions:
    issues: write
    pull-requests: write
    contents: read

jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/stale@v8
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  stale-issue-message: "This issue has been automatically marked as stale becuase it does not have recent activity."
                  days-before-stale: 1
                  days-before-close: 5
