name: Simple Github Actions Demo
on: [push]

jobs:
    simple-action:
        runs-on: ubuntu-latest
        steps:
            - name: Simple Js Action
              id: greet
              uses: actions/hello-world-javascript-action@v1.1
              with:
                  who-to-greet: "shubham saini"
            - name: Log Greeting Time
              run: echo "Greeting time was ${{steps.greet.outputs.time}}"
